### ISSUE TITLE
testing run time error

### ISSUE THREAD

**Issue by helloyuning** [zju3dv/clean-pvnet#219]
At first, thank for your sharing and woderful work
I tried to run test cat model, but I got error as follows:

Load model: data/model/pvnet/cat/199.pth
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
  0%|                                                                                                           | 0/1002 [00:48<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 276, in <module>
    if __name__ == '__main__':
  File "run.py", line 78, in run_evaluate
    with torch.no_grad():
  File "/home/ivclab/anaconda3/envs/pv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/pvnet/resnet18.py", line 79, in forward
    x2s, x4s, x8s, x16s, x32s, xfc = self.resnet18_8s(x)
  File "/home/ivclab/anaconda3/envs/pv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/pvnet/resnet.py", line 203, in forward
    x2s = self.relu(x)
  File "/home/ivclab/anaconda3/envs/pv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ivclab/anaconda3/envs/pv/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 99, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/ivclab/anaconda3/envs/pv/lib/python3.7/site-packages/torch/nn/functional.py", line 941, in relu
    result = torch.relu_(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device

And I reinstall cuda, gcc, almost all the dependences, but It's still not working.
Can you give me some advices?
My environment: 
cuda = 9.0
gcc-5.4.0 and g++-5.4.0
python3.7

**Comment by BoBoINVIDICUS** [comment]
Hello, I have the same problem as you, could you tell me how to solve this problem?

**Comment by helloyuning** [comment]
> 

Hello, BoBoINVIDICUS.
I solved this problem by changing pytorch version.
GPU with compute capability 7 only support torch 10+ version, in my case, I have GPU with compute capability 8.6 is imcompatable with torch 10. So I think It is important to check the torch version supported by your GPU.
Hope this can help you.

**Comment by BoBoINVIDICUS** [comment]
> 

Thank you very much for your reply. I will change my Pytorch version and try again. Wish you a nice day!

**Comment by ShawanDeba** [comment]
> > 
> 
> Thank you very much for your reply. I will change my Pytorch version and try again. Wish you a nice day!

Hey I have been facing the same problem. 
Torch Version:1.1.0
Cuda:1.12
NVIDIA GeForce RTX 4080
