### ISSUE TITLE
我在Ubuntu20.04下运行报错

### ISSUE THREAD

**Issue by BoBoINVIDICUS** [zju3dv/clean-pvnet#230]
我的系统是Ubuntu20.04，cuda 版本为10.0,
当我运行以下指令时：python run.py --type evaluate --cfg_file configs/linemod.yaml model cat cls_type cat
Load model: data/model/pvnet/cat/199.pth
报错结果如下：
Load model: data/model/pvnet/cat/199.pth
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
  0%|                                                  | 0/1002 [00:45<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 276, in <module>
    globals()['run_'+args.type]()
  File "run.py", line 78, in run_evaluate
    output = network(inp)
  File "/home/akon/anaconda3/envs/pvnet-cuda-10.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/pvnet/resnet18.py", line 79, in forward
    x2s, x4s, x8s, x16s, x32s, xfc = self.resnet18_8s(x)
  File "/home/akon/anaconda3/envs/pvnet-cuda-10.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "lib/networks/pvnet/resnet.py", line 203, in forward
    x2s = self.relu(x)
  File "/home/akon/anaconda3/envs/pvnet-cuda-10.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/akon/anaconda3/envs/pvnet-cuda-10.0/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 99, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/akon/anaconda3/envs/pvnet-cuda-10.0/lib/python3.7/site-packages/torch/nn/functional.py", line 941, in relu
    result = torch.relu_(input)
RuntimeError: CUDA error: no kernel image is available for execution on the device

您能告诉我是出了什么问题吗？谢谢

**Comment by pengsida** [comment]
https://github.com/pytorch/pytorch/issues/31285

**Comment by BoBoINVIDICUS** [comment]
然後我把pytorch版本改爲了1.13.0,再運行這個指令時：python setup.py build_ext --inplace出現了新的錯誤：
In file included from /home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/include/ATen/Tensor.h:3,
                 from /home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:3,
                 from /home/akon/clean-pvnet/lib/csrc/ransac_voting/src/ransac_voting.cpp:1:
/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/include/ATen/core/TensorBody.h:216:30: note: declared here
  216 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1906, in _run_ninja_build
    env=env)
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    'build_ext': BuildExtension
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 554, in build_extension
    depends=ext.depends,
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 668, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1578, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/akon/anaconda3/envs/pvnet-cuda-11.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
內容太多，我只截取了部分的

**Comment by mlmlh** [comment]
Hi Bobo, have you solved this problem? I have the same issue with Torch: 2.0.1, cuda 11.8...

**Comment by BoBoINVIDICUS** [comment]
> Hi Bobo, have you solved this problem? I have the same issue with Torch: 2.0.1, cuda 11.8...
Later, I changed the CUDA version to 11.1 and it worked, and my NVIDIA GeForce version is 30 series.
