### ISSUE TITLE
GPU问题

### ISSUE THREAD

**Issue by 545464598** [zju3dv/clean-pvnet#77]
你好，我在训练的时候报了这个错误AssertionError: 
The NVIDIA driver on your system is too old (found version 9010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.
(pvnet) yanhao@amax:~/path/to/clean-pvnet$ ncidia-smi
ncidia-smi: command not found
(pvnet) yanhao@amax:~/path/to/clean-pvnet$ nvidia-smi
Sun Apr 26 21:30:59 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.77                 Driver Version: 390.77                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN Xp            Off  | 00000000:02:00.0  On |                  N/A |
| 26%   46C    P8    18W / 250W |     94MiB / 12195MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            Off  | 00000000:81:00.0 Off |                  N/A |
| 27%   46C    P8    18W / 250W |    559MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2174      G   /usr/lib/xorg/Xorg                            82MiB |
|    1     12535      C   /usr/bin/python3.5                           547MiB |
+-----------------------------------------------------------------------------+

**Comment by 545464598** [comment]
请问，可以更改程序去实现吗？

**Comment by pengsida** [comment]
不可以。这是nvidia驱动版本不符。

**Comment by 545464598** [comment]
哦哦，谢谢，问题解决了
